#!/bin/bash

jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
jupyter nbextension install --py jupytext --user
jupyter nbextension enable --py jupytext
jupyter labextension install jupyterlab-jupytext@0.19
jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.38
jupyter lab build
