#!/bin/bash

# run matplotlib once to generate the font cache
python -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"

test -e test.png && rm test.png

jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
jupyter nbextension install --py jupytext --user
jupyter nbextension enable --py jupytext
jupyter labextension install @jupyterlab/latex
jupyter labextension install jupyterlab-jupytext@0.19
jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.38
jupyter lab build
